import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Button } from "@mantine/core";
import imgSrc from "../public/golden-horizon-logo.png";
import { useRouter } from "next/router";
import { useMediaQuery } from "@mantine/hooks";
import DefaultButton from "../src/components/buttons/DefaultButton";
import { FaSearch, FaWhatsapp } from "react-icons/fa";
import { getDocs, collection } from "firebase/firestore";
import { db } from "../lib/firebase.config";
import {QuerySnapshot, DocumentData} from "firebase/firestore"
import { GetServerSideProps } from "next";

const Home: NextPage = () => {
    const router = useRouter()
  const isDesktop = useMediaQuery("(min-width: 695px)", false);

  return (
    <div className="landing-page__container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="landing-page__logo-container">
        <Image priority={true} src={imgSrc} layout="responsive" />
      </div>
      <Button onClick={() => router.push(isDesktop ? "/listings" : "/filter")}>Browse Listings</Button>
    </div>
  );
};



export default Home;
