import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Button } from "@mantine/core";
import imgSrc from "../public/golden-horizon-logo.png";
import DefaultButton from "../src/components/buttons/DefaultButton";
import { FaSearch, FaWhatsapp } from "react-icons/fa";

const Home: NextPage = () => {
  return (
    <div className="landing-page__container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="landing-page__logo-container">
        <Image priority={true} src={imgSrc} layout="responsive" />
      </div>
      <DefaultButton>Get Started</DefaultButton>
    </div>
  );
};

export default Home;
