import Navbar from "../components/navigation/Navbar";
import { NavigationProvider } from "../context/navigationContext";
import { AuthUserProvider } from "../context/authUserContext";
import Head from "next/head";
import { FaWhatsapp, FaFacebook, FaInstagram } from "react-icons/fa";
import { AiOutlineMail } from "react-icons/ai";
import { ActionIcon } from "@mantine/core";
import Show from "../components/HOC/Show";

type Props = {
  children: React.ReactNode;
};

export default function MainLayout({ children }: Props) {
  return (
      <NavigationProvider>
        <>
          <Head>
            <title>Horizon Real Estate</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className="nav-offset"></div>
          <Navbar />
          <main className="main-layout__main">{children}</main>
          <Show blacklistRoutes={["/listings/[id]"]}>
            <footer className="flow-content">
              <div className="footer__header">
                <h1>Horizon Real Estate</h1>
                <div>
                  <a href="https://web.facebook.com/horizonbienesraices22">
                    <FaFacebook size={32} />
                  </a>
                  <a href="https://instagram.com/horizonbienesraices?igshid=YmMyMTA2M2Y=">
                    <FaInstagram size={32} />
                  </a>
                </div>
              </div>
              <div>
                <FaWhatsapp size={32} />
                <a href="https://wa.me/526251459646">625 145 9646</a>
              </div>
              <div>
                <AiOutlineMail size={32} />
                <a href="mailto: info@horizonrealty.com.mx">
                  info@horizonrealty.com.mx
                </a>
              </div>
            </footer>
          </Show>
        </>
      </NavigationProvider>
  );
}
