import Navbar from "../components/navigation/Navbar";
import { NavigationProvider } from "../context/navigationContext";
import { AuthUserProvider } from "../context/authUserContext";
import Head from "next/head"

type Props = {
  children: React.ReactNode;
};

export default function MainLayout({ children }: Props) {
  return (
    <AuthUserProvider>
      <NavigationProvider>
        <>
          <Head>
            <title>Horizon Real Estate</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar />
          <main>{children}</main>
        </>
      </NavigationProvider>
    </AuthUserProvider>
  );
}
